// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiteHairStylist.Data;

#nullable disable

namespace SiteHairStylist.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240520202725_orice")]
    partial class orice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SiteHairStylist.Models.Inregistrare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Inregistrare");
                });

            modelBuilder.Entity("SiteHairStylist.Models.Pret", b =>
                {
                    b.Property<int>("PriceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriceID"));

                    b.Property<int?>("ServiceID")
                        .HasColumnType("int");

                    b.Property<int?>("ServiciuServiceID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Suma")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("PriceID");

                    b.HasIndex("ServiciuServiceID");

                    b.ToTable("Pret");
                });

            modelBuilder.Entity("SiteHairStylist.Models.ProgramDeLucru", b =>
                {
                    b.Property<int>("WorkScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkScheduleID"));

                    b.Property<TimeSpan>("OraDeschidere")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("OraInchidere")
                        .HasColumnType("time");

                    b.Property<string>("ZiuaSaptamanii")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkScheduleID");

                    b.ToTable("ProgramDeLucru");
                });

            modelBuilder.Entity("SiteHairStylist.Models.Programari", b =>
                {
                    b.Property<int>("AppointmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentID"));

                    b.Property<DateTime>("DataOraProgramarii")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ServiceID")
                        .HasColumnType("int");

                    b.Property<int?>("ServiciuServiceID")
                        .HasColumnType("int");

                    b.Property<string>("Stare")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppointmentID");

                    b.HasIndex("ServiciuServiceID");

                    b.ToTable("Programari");
                });

            modelBuilder.Entity("SiteHairStylist.Models.Recenzii", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<string>("Comentariu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataPostarii")
                        .HasColumnType("datetime2");

                    b.Property<int>("Evaluare")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceID")
                        .HasColumnType("int");

                    b.Property<int?>("ServiciuServiceID")
                        .HasColumnType("int");

                    b.HasKey("ReviewID");

                    b.HasIndex("ServiciuServiceID");

                    b.ToTable("Recenzii");
                });

            modelBuilder.Entity("SiteHairStylist.Models.Servicii", b =>
                {
                    b.Property<int?>("ServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("ServiceID"));

                    b.Property<string>("Descriere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Durata")
                        .HasColumnType("int");

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServiceID");

                    b.ToTable("Servicii");
                });

            modelBuilder.Entity("SiteHairStylist.Models.Pret", b =>
                {
                    b.HasOne("SiteHairStylist.Models.Servicii", "Serviciu")
                        .WithMany("Preturi")
                        .HasForeignKey("ServiciuServiceID");

                    b.Navigation("Serviciu");
                });

            modelBuilder.Entity("SiteHairStylist.Models.Programari", b =>
                {
                    b.HasOne("SiteHairStylist.Models.Servicii", "Serviciu")
                        .WithMany("Programari")
                        .HasForeignKey("ServiciuServiceID");

                    b.Navigation("Serviciu");
                });

            modelBuilder.Entity("SiteHairStylist.Models.Recenzii", b =>
                {
                    b.HasOne("SiteHairStylist.Models.Servicii", "Serviciu")
                        .WithMany("Recenzii")
                        .HasForeignKey("ServiciuServiceID");

                    b.Navigation("Serviciu");
                });

            modelBuilder.Entity("SiteHairStylist.Models.Servicii", b =>
                {
                    b.Navigation("Preturi");

                    b.Navigation("Programari");

                    b.Navigation("Recenzii");
                });
#pragma warning restore 612, 618
        }
    }
}
